services:
#  mssql:
#    image: mcr.microsoft.com/mssql/server:2022-latest
#    container_name: mssqlserver         # tên container
#    hostname: mssql
#    environment:
#      MSSQL_SA_PASSWORD: root@123          #Thiết lập password
#      ACCEPT_EULA: Y
#      # Express:
#
#    volumes:
#      - ../db/data:/var/opt/mssql/data # thư mục lưu DB
#      - ../db/bk:/var/opt/mssql/backup      # thư  mục chứa file backup
#    ports:
#      - "1433:1433"                     # cổng kết nối
  mysql:
    image: mysql:8.0
    container_name: mysqlserver
    hostname: mysql
    environment:
      MYSQL_DATABASE: QuanLyGiaiVoDichBongDa
      MYSQL_ROOT_PASSWORD: root@123
    volumes:
      - ../db/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root@123
    ports:
      - "8081:80"
    depends_on:
      - mysql